title: Crypto Palm Beach
email: cryptopalmbeach@proton.me
description: Another Filippo Albertin Site
twitter_username: creativephil75
github_username:  cryptopalmbeach
bluesky_username: filippoalbertin

# Build settings
theme: minima
plugins:
  - jekyll-feed

